In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
inventory = pd.read_csv(
    "../data/processed/inventory_cleaned.csv"
)

inventory.head()

,Product ID,Store ID,Stock Levels,Supplier Lead Time (days),Stockout Frequency,Reorder Point,Expiry Date,Warehouse Capacity,Order Fulfillment Time (days)
0,9286,16,700,10,14,132,2024-01-15,1052,6
1,2605,60,82,11,1,127,2024-12-16,1262,9
2,2859,55,145,25,14,192,2024-04-30,1457,12
3,2374,24,151,17,6,19,2024-12-16,2944,3
4,7678,5,714,12,2,21,2024-08-05,3739,7

In [4]:
inventory.describe()

,Product ID,Store ID,Stock Levels,Supplier Lead Time (days),Stockout Frequency,Reorder Point,Warehouse Capacity,Order Fulfillment Time (days)
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5534.614600,50.192900,502.119000,15.050000,9.495300,104.617500,2998.757400,7.544600
std,2619.330826,28.656605,288.888252,8.446362,5.774384,54.883156,1158.289745,4.036637
min,1000.000000,1.000000,0.000000,1.000000,0.000000,10.000000,1000.000000,1.000000
25%,3235.750000,25.000000,253.000000,8.000000,5.000000,57.000000,1971.500000,4.000000
50%,5559.000000,50.000000,498.000000,15.000000,9.000000,105.000000,3016.000000,7.000000
75%,7841.250000,75.000000,751.000000,22.000000,15.000000,152.000000,4011.000000,11.000000
max,9998.000000,99.000000,999.000000,29.000000,19.000000,199.000000,4999.000000,14.000000

Low Stock Products

In [5]:
low_stock = inventory[
    inventory["Stock Levels"]
    < inventory["Reorder Point"]
]

print("Low Stock Products:", len(low_stock))

Low Stock Products: 1050

Stockout risk products

In [6]:
high_risk = inventory[
    inventory["Stockout Frequency"] > 15
]

print("High Risk Products:", len(high_risk))

High Risk Products: 2000

Warehouse Utilization

In [7]:
inventory["Warehouse Utilization"] = (
    inventory["Stock Levels"]
    /
    inventory["Warehouse Capacity"]
)

inventory["Warehouse Utilization"].describe()

count    10000.000000
mean         0.202837
std          0.164037
min          0.000000
25%          0.083720
50%          0.166810
75%          0.269587
max          0.995015
Name: Warehouse Utilization, dtype: float64

Inventry alert flag

In [8]:
inventory["Inventory Alert"] = (
    inventory["Stock Levels"]
    < inventory["Reorder Point"]
).astype(int)

inventory["Inventory Alert"].value_counts()

Inventory Alert
0    8950
1    1050
Name: count, dtype: int64